[package]
edition = "2021"
name = "udemy_rocket"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0-rc", features = ["json"]}
serde_json = "1.0"
